applications/account/urls.py
from django.urls import path,include
from . import views

app_name='account'

urlpatterns = [

    path('profile/', views.user_data, name='p'),
    path('register/', views.register, name='register'),


]

djangoVue/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('applications.Listelement.urls')),
    path('accounts/', include('applications.account.urls')),
    path('', include('applications.store.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('social-auth/', include('social_django.urls', namespace='social')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# https://testdjango.com:8000/social-auth/complete/google-oauth2/
# https://testdjango.com:8000/social-auth/complete/facebook/
# https://testdjango.com:8000/social-auth/complete/live/
# https://testdjango.com:8000/social-auth/complete/azuread-oauth2/
# https://testdjango.com:8000/social-auth/complete/azuread-tenant-oauth2/

templates/register.html
<!DOCTYPE html>
<html>

<head>
        <title>Login Page</title>
        <!--Made with love by Mutiullah Samim -->

        <!--Bootsrap 4 CDN-->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
                integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO"
                crossorigin="anonymous">

        <!--Fontawesome CDN-->
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css"
                integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU"
                crossorigin="anonymous">

        <!--Custom styles-->
        <link rel="stylesheet" type="text/css" href="styles.css">

        <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet"
                id="bootstrap-css">
        <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
        <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
        <!------ Include the above in your HEAD tag ---------->

        <style>
                /* Made with love by Mutiullah Samim*/

                @import url('https://fonts.googleapis.com/css?family=Numans');

                html,
               

                .container {
                        height: 100%;
                        align-content: center;
                }

                .card {
                        height: 370px;
                        margin-top: auto;
                        margin-bottom: auto;
                        width: 400px;
                        
                }

                .social_icon span {
                        font-size: 60px;
                        margin-left: 10px;
                        color: #FFC312;
                }

                .social_icon span:hover {
                        color: white;
                        cursor: pointer;
                }

                .card-header h3 {
                        color: white;
                }

                .social_icon {
                        position: absolute;
                        right: 20px;
                        top: -45px;
                }

                .input-group-prepend span {
                        width: 50px;
                        background-color: #FFC312;
                        color: black;
                        border: 0 !important;
                }

                input:focus {
                        outline: 0 0 0 0 !important;
                        box-shadow: 0 0 0 0 !important;

                }

                .remember {
                        color: white;
                }

                .remember input {
                        width: 20px;
                        height: 20px;
                        margin-left: 15px;
                        margin-right: 5px;
                }

                .login_btn {
                        color: black;
                        background-color: #FFC312;
                        width: 100px;
                }

                .login_btn:hover {
                        color: black;
                        background-color: white;
                }

                .links {
                        color: white;
                }

                .links a {
                        margin-left: 4px;
                }
        </style>
</head>

<body>
        <div class="container">
                <div class="d-flex justify-content-center h-100">
                        <div class="card">
                                <div class="card-header">
                                        <h3>Sign In</h3>
                                        <div class="d-flex justify-content-end social_icon">
                                                <span><i class="fab fa-facebook-square"></i></span>
                                                <span><i class="fab fa-google-plus-square"></i></span>
                                                <span><i class="fab fa-twitter-square"></i></span>
                                        </div>
                                </div>


                                <div class="">
                                        {% if form.errors %}
                                        <p class="text-white">Your username and password didn't match. Please try again.
                                        </p>
                                        {% endif %}

                                        {% if user.is_authenticated %}
                                        <p class="text-white">esta autenticado</p>
                                        {% else %}
                                        <p class="text-white">Please login to see this page.</p>
                                        {% endif %}

                                        <form method="post" action="{% url 'account:register' %}">
                                                {% csrf_token %}
                                                <div class="input-group form-group">
                                                        <div class="input-group-prepend">
                                                                <span class="input-group-text"><i
                                                                                class="fas fa-user"></i></span>
                                                        </div>
                                                        {{form.as_p }}

                                                </div>

                                                <div class="form-group">
                                                        <input type="submit" value="login"
                                                                class="btn float-right login_btn">
                                                        <input type="hidden" name="next" value="{{ next }}">
                                                </div>
                                        </form>
                                </div>
                                <div class="card-footer">

                                        <div class="d-flex justify-content-center">
                                                <a href="{% url 'password_reset' %}">olvido su contraseña</a>
                                        </div>
                                </div>
                        </div>
                </div>
        </div>
</body>

</html>

templates/user_data.html
<p>
        <a href="{% url 'login' %} ">
                login
        </a>

        
        {% if  user.userprofile%}
         <img src="{{MEDIA_URL}}{{user.userprofile.avatar}} " alt="" srcset="" width="5%" height="10%">
                
        {% else %}
        <h1>no hya imagen</h1>
        {% endif %}
                

        <form action="" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{form}}
                <input type="submit" value="imagen">
        </form>

        {{user.username}}
        {{user.is_authenticated}}
        {{user.email}}
</p>