applications/store/urls.py
from django.urls import path,include
from . import views

app_name='store'

urlpatterns = [

    path('', views.index, name='inicio'),

    
    #paypal

    path('product/pay/paypal/<int:pk>', views.make_pay_paypal, name='make_pay_paypal'),
    path('product/pay/paypal/<int:pk>/<str:code>', views.make_pay_paypal, name='make_pay_paypal'),
    path('product/paypal/success/<int:pk>', views.paypal_success, name='paypal_success'),
    path('product/paypal/success/<int:pk>/<str:code>', views.paypal_success, name='paypal_success'),
    path('product/paypal/cancel', views.paypal_cancel, name='paypal_cancel'),


    path('product/payed/detail/<int:pk>', views.datail_pay, name='datail_pay'),

    path('bought/', views.bought, name='bought'),

    # path('product/<int:pk>', views.DetailsElement.as_view(), name='detalle'),
    # path('product/<slug:url_clean>', views.DetailsElement.as_view(), name='detalle'),

    #cupon
    path('product/cupon-apply', views.cuponApply, name='cuponApply'),

    path('product/<slug:url_clean>', views.detail, name='detalle'),

    #cupon
    path('product/<slug:url_clean>/<str:code>', views.detail, name='detalle'),



    # path('product/<int:pk>/<slug:url_clean>', views.DetailsElement.as_view(), name='detalle'),




]

djangoVue/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('applications.Listelement.urls')),
    path('accounts/', include('applications.account.urls')),
    path('', include('applications.store.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('social-auth/', include('social_django.urls', namespace='social')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# https://testdjango.com:8000/social-auth/complete/google-oauth2/
# https://testdjango.com:8000/social-auth/complete/facebook/
# https://testdjango.com:8000/social-auth/complete/live/
# https://testdjango.com:8000/social-auth/complete/azuread-oauth2/
# https://testdjango.com:8000/social-auth/complete/azuread-tenant-oauth2/

applications/Listelement/models.py
from django.db import models
from decimal import Decimal
# from stdimage import StdImageField, JPEGField

from django.dispatch import receiver

import os

# Create your models here.

class Category(models.Model):
    title = models.CharField( max_length=255)
    url_clean = models.CharField( max_length=255)
    
    def __str__(self):
        return self.title
    
class Type(models.Model):
    title = models.CharField( max_length=255)
    url_clean = models.CharField( max_length=255)

    def __str__(self):
        return self.title

class Element(models.Model):
    title = models.CharField( max_length=255)
    url_clean = models.CharField( max_length=255)
    description = models.TextField()
    price = models.DecimalField(max_digits=10,decimal_places=2, default=60.0)
    #un elemento va apermanecer a una categoria
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    #para activar cierto campo
    type = models.ForeignKey(Type, on_delete=models.CASCADE)

    def get_discount(self,cupon):
        return (cupon.discount / Decimal(100))* self.price  #  10/100 = 0.1* 10= 1

    def get_price_after_discount(self,cupon):
        return self.price - self.get_discount(cupon)

    
    def __str__(self):
        return self.title


class ElementeImages(models.Model):
    element = models.ForeignKey(Element, on_delete=models.CASCADE)
    title = models.CharField(max_length=255)
    cover= models.ImageField(upload_to='images/')


    def __str__(self):
        return self.title # TODO


@receiver(models.signals.post_delete,sender=ElementeImages)
def auto_delete_file_on_delete(sender,instance, **kwargs):
    if instance.cover:
        if os.path.isfile(instance.cover.path):
            os.remove(instance.cover.path)


@receiver(models.signals.pre_save,sender=ElementeImages)
def auto_delete_file_on_delete(sender,instance, **kwargs):

    if not instance.pk:
        return False

    try:

        old_file = ElementeImages.objects.get(pk=instance.pk).cover

    except ElementeImages.DoesNotExist:
        return False

    new_file = instance.cover

    if not old_file == new_file:
        if instance.cover:
            if os.path.isfile(old_file.path):
                os.remove(old_file.path)

applications/store/models.py
from django.db import models
from django.contrib.auth.models import User
from applications.Listelement.models import Element

from django.core.validators import MinValueValidator, MaxValueValidator



# Create your models here.

class Cupon(models.Model):
    code = models.CharField(max_length=60, unique=True)
    valid_from =models.DateTimeField()
    valid_to =models.DateTimeField()
    discount= models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(100)])
    active = models.BooleanField()

    def __str__(self):
        return self.code

class Payment(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now_add=True)    
    payment_id = models.CharField( max_length=255)
    payer_id = models.CharField( max_length=255)

    price = models.DecimalField(max_digits=10,decimal_places=2, default=60.00)
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    element = models.ForeignKey(Element, on_delete=models.CASCADE)
    cupon = models.ForeignKey(Cupon,on_delete=models.CASCADE, null=True)
    discount = models.DecimalField(max_digits=10,decimal_places=2, null=True)
    price_discount = models.DecimalField(max_digits=10,decimal_places=2, null=True)
    

    @classmethod
    def create(cls,payment_id, payer_id, price,user_id,element_id ):
        payment=cls(
            payment_id=payment_id, 
            payer_id= payer_id,
            price=price,
            element_id=element_id,
            user_id=user_id
        )
        return payment

    def __str__(self):
        return self.price


class Message(models.Model):
    element= models.ForeignKey(Element, on_delete=models.CASCADE, related_name='element_cooments')
    name = models.CharField(max_length=30)
    lastname = models.CharField(max_length=30)
    email = models.EmailField()
    body = models.TextField()
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now=True)
    activate = models.BooleanField(default=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)

    class Meta:
        ordering=('created',)
    def __str__(self):
        return "Comentario de {self.name} en {self.element}"

applications/store/forms.py
from .models import *
from django import forms


class MessageForm(forms.ModelForm):
    class Meta:
        model = Message
        fields = ('name', 'email','body')


class CuponForm(forms.Form):
    code= forms.CharField()
    element_id= forms.CharField(widget=forms.HiddenInput())

applications/store/views.py
from django.http.response import HttpResponseNotFound
from django.shortcuts import reverse, render, redirect, get_object_or_404
from django.views.generic import (DetailView)
from django.contrib.auth.decorators  import login_required
from django.views.decorators.http import require_POST
from django.conf import settings
from django.utils import timezone
from django.http import HttpResponseNotFound


from applications.Listelement.models import Element,Category
from django.core.paginator import Paginator

from .forms import *


from paypalcheckoutsdk.core import PayPalHttpClient, SandboxEnvironment
from paypalcheckoutsdk.orders import OrdersCreateRequest,OrdersCaptureRequest
from paypalhttp import HttpError

from .models import *



# Create your views here.


def index (request):
    

    search =request.GET.get('search') if request.GET.get('search') else ''
    category_id = request.GET.get('category_id')
    category_id= int(category_id) if category_id else ''

    if search:
        elements =  Element.objects.filter(title__contains=search)
    else:
        elements =  Element.objects

    if category_id:
        elements =  elements.filter(category_id=category_id)


    elements =  elements.all()
    category =  Category.objects.all()

    paginator = Paginator(elements,5)

    page_number = request.GET.get('page')
    elements_page = paginator.get_page(page_number)
    return render(request,'store/index.html', {'elements': elements_page,'category': category,'search': search, 'category_id':category_id })


def detail(request,url_clean,code=None):

    # print(code)
    # if code == None:
    #     print(code)

    cupon = get_valid_cupon(code) if code else None
    msj_cupon = ''
    if (code == 'None' or cupon is None) and code is not None :
        msj_cupon = 'Cupón invalido'
        code = ''


    element = get_object_or_404(Element, url_clean = url_clean)
    #mensajes que tienen configudos los elementos
    message= element.element_cooments.filter(activate=True)
    message_form= MessageForm()
    cupon_form= CuponForm(initial={'element_id':element.id,'code':code })

    message_new=None

    if request.method == 'POST': #recibiendo el formulario
        message_form =MessageForm(data=request.POST)
        if message_form.is_valid():
            message_new =message_form.save(commit=False)
            message_new.element = element
            #comentario por usuario
            # if request.user.is_authenticated:
            message_new.save()
            message_form= MessageForm() #para cuando guarde boore lo que hay en el form(data)

    return render(request,'store/detalleElement.html',{'element':element,
                                                        'message_form':message_form,
                                                        'message_new':message_new,
                                                        'message':message,
                                                        'cupon_form':cupon_form,
                                                        'cupon':cupon,
                                                        'msj_cupon':msj_cupon
    })


@require_POST  #para que sea accedida solo mediante post
def cuponApply(request):
    
    form = CuponForm(request.POST)
    cupon=None
    
    if form.is_valid():
        code = form.cleaned_data['code']
        elementId = form.cleaned_data['element_id']

    #si el cupon es valido

    try:
        cuponModel = get_valid_cupon(code)

        if cuponModel:
            cupon = cuponModel.code

    except Cupon.DoesNotExist:
        pass

    #si el elemento es valido
    try:
        element = Element.objects.get(id=elementId) 
    except Element.DoesNotExist:
        cupon=None

    return redirect('store:detalle',url_clean=element.url_clean, code=cupon)


class DetailsElement(DetailView):
    model = Element
    template_name='store/detalleElement.html'
    slug_field = 'url_clean'
    slug_url_kward = 'url_clean'


@login_required
def make_pay_paypal(request,pk, code=None):
    #validar el cupon
    cupon = get_valid_cupon(code) if code else None

    #cupon invalido

    if cupon is None and code is not None:
        #aca se puede redirigir a una pagina de 404
        print('entro acá')
        return HttpResponseNotFound()

    element= get_object_or_404(Element, pk = pk)

    if cupon: 
        return_url =  f"https://testdjango.com:8000/product/paypal/success/{element.id}/{cupon.code}"
        # return_url =  "http://127.0.0.1:8000/product/paypal/success/%s/%s"%(element.id,cupon.code)
        price= round(element.get_price_after_discount(cupon),2)
    else:
        return_url =  f"https://testdjango.com:8000/product/paypal/success/{element.id}"
        price= element.price  
    
    # Creating Access Token for Sandbox
    client_id = settings.PAYPAL_CLIENT_ID
    client_secret = settings.PAYPAL_CLIENT_SECRET
    # Creating an environment
    environment = SandboxEnvironment(client_id=client_id, client_secret=client_secret)
    client = PayPalHttpClient(environment)
    
    
    requestPaypal = OrdersCreateRequest()

    requestPaypal.prefer('return=representation')

    requestPaypal.request_body (
        {
            "intent": "CAPTURE",
            "purchase_units": [
                {
                    "amount": {
                        "currency_code": "USD",
                        "value": str(price),
                    }
                }
            ],
            "application_context":{
                "return_url": return_url,
                "cancel_url": "http://127.0.0.1:8000/produt/paypal/cancel"
            }
        }
    )
    
    try:
        response=client.execute(requestPaypal)

        if response.result.status == "CREATED":
            
            approval_url=str(response.result.links[1].href)
            print (approval_url)
            return render(request, 'store/paypal/buy.html',{'element':element,'approval_url':approval_url})

    except IOError as ioe:
        
        print (ioe)
        if isinstance(ioe, HttpError):
            # Something went wrong server-side
            print (ioe.status_code)


@login_required
def paypal_success(request, pk, code=None):

    cupon = get_valid_cupon(code) if code else None


    # Creating Access Token for Sandbox
    client_id = settings.PAYPAL_CLIENT_ID
    client_secret = settings.PAYPAL_CLIENT_SECRET
    # Creating an environment
    environment = SandboxEnvironment(client_id=client_id, client_secret=client_secret)
    client = PayPalHttpClient(environment)

    element = get_object_or_404(Element, pk=pk)

    ordenId = request.GET.get('token')
    payerid = request.GET.get('PayerID')

    requestPaypal = OrdersCaptureRequest(ordenId)

    try:
        # if requestPaypal.excecute({'payer_id':payerid}):
        response = client.execute(requestPaypal)

        paymentModel = Payment.create (
            payment_id=ordenId, 
            payer_id= payerid,
            price=element.price,
            element_id=element.id,
            user_id=request.user.id
        )

        if cupon:
            paymentModel.cupon= cupon
            paymentModel.discount = element.get_price_after_discount(cupon)
            paymentModel.price_discount= element.get_discount(cupon)
            cupon.active=0
            cupon.save()

        paymentModel.save()

        return redirect(reverse('store:datail_pay', args=[paymentModel.id]))

            # If call returns body in response, you can get the deserialized version from the result attribute of the response
        order = response.result.id
    except IOError as ioe:
        if isinstance(ioe, HttpError):
            # Something went wrong server-side
            print (ioe.status_code)
            print (ioe.headers)
            print (ioe)
        else:
            # Something went wrong client side
            print (ioe)

    return render(request, 'store/paypal/success.html')


@login_required
def datail_pay(request, pk):
    payment= get_object_or_404(Payment, pk=pk)
    return render(request, 'store/payment/detail-payed.html', {'payment': payment})


@login_required
def bought(request):
    return render(request, 'store/payment/bought.html', {'payments': Payment.objects.select_related('element').filter(user=request.user)})


@login_required
def paypal_cancel(request):

    return render(request, 'store/paypal/cancel.html')


def get_valid_cupon(code):
    now = timezone.now()

    cupon= None
    try:

        cuponModel = Cupon.objects.get(code__iexact=code, #iexact que sea exacto el valor 
                valid_from__lte=now, #less than or equal to = menor igual a= la fecha  es igual o menor a la fecha del cupon
                valid_to__gte=now, #great than or equal to = mayyor igual a= la fecha  es igual o mayor a la fecha del cupon
                active=True
        ) 

        cupon=cuponModel

    except Cupon.DoesNotExist:
        pass

    return cupon

templates/store/detalleElement.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
            <!--Bootsrap 4 CDN-->
            <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
            integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO"
            crossorigin="anonymous">
            <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta2/css/all.min.css" integrity="sha512-YWzhKL2whUzgiheMoBFwW8CKV4qpHQAEuvilg9FAn5VJUDwKZZxkJNuGM4XkWuk94WCrrwslk8yWNGmY1EduTA==" crossorigin="anonymous" referrerpolicy="no-referrer" />

    <!--Fontawesome CDN-->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css"
            integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU"
            crossorigin="anonymous">

    <!--Custom styles-->
    <link rel="stylesheet" type="text/css" href="styles.css">

    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet"
            id="bootstrap-css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <!------ Include the above in your HEAD tag ---------->
</head>
<body class="container">
    <h1> hola mundo</h1>

        <div class="card-header mt-2"></div>
        <div class="card">
            <img src="/uploads/{{element.elementeimages_set.all.0.cover}} " alt="{{e.elementeimages_set.all.0.title}}"  width="30%" height="30%" >
            <div class="card-body">
            <h1>
                {{element.title}} ||||| precio = {{element.price}} 


            </h1>
                
                {% if  cupon %}
                {% include  'store/fragment/detail_cupon.html' %}
                    
                {% endif %}
                    


            {% with message.count as total_comments %}

                <h6>
                    {{total_comments}}  <i class="fas fa-comment "></i> comentario{{total_comments| pluralize}}
                </h6>
                <div>
                    {{element.description}}
                </div>

            {% endwith %}

                {% if cupon %}
                <a href=" {% url 'store:make_pay_paypal' element.id cupon.code %}">compar por paypal</a>

                {% else %}
                <a href=" {% url 'store:make_pay_paypal' element.id %}">compar por paypal</a>

                {% endif %}

            <details>
                <summary>¿Tienes un descuento? {% if msj_cupon %}
                    <span>{{msj_cupon}}</span>
                {% endif %}</summary>
                
                

                <form id="cupon" action="{% url 'store:cuponApply' %} " method="POST">
                    {% csrf_token %}

                    {{cupon_form}}
                    <button type="submit">agregar cupon</button>
                </form>
            </details>
        </div>
    </div>

    <div>
        
        {% for m in message %}

            <p>{{m.counter}}  por {{m.name}} {{m.created}}:
               {{m.body}} 
            </p>

            {% empty %}
            <p>Sin comentarios</p>
            
        {% endfor %}
            
    </div>

    
    
    {% if user.is_authenticated  %}
    <div>
        <form action="" method="post">
            {% csrf_token %}

            {% if form.errors %}

                <p>{{form.errors}}</p>

            {% endif %}

            {{message_form.as_p}}
            <button type="submit">enviar</button>

        </form>
    </div>

    {% endif %}
        


</body>
</html>

templates/store/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <!--Bootsrap 4 CDN-->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
        integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <!--Fontawesome CDN-->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css"
        integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">

    <!--Custom styles-->
    <link rel="stylesheet" type="text/css" href="styles.css">

    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <!------ Include the above in your HEAD tag ---------->
</head>

<body class="container h-75">

    <h1> Tienda la esquina</h1>

    <form method="get" class="form-inline">
        <input type="text" name="search" id="  " value="{{search}}" class="form-control w-75">
        <select name="category_id" id="" class="form-control">
            <option value="">sin selección</option>
            {% for c in category %}
            <option value="{{c.id}}" {% if category_id == c.id %} selected {% endif %}>{{c.title}} </option>
            {% endfor %}

        </select>

        <button type="submit">Buscar</button>

    </form>
    <div class="row">

        {% for e in elements %}
        <div class="col-6">
          
            <div class="card">
                <div class="card-body">

                
                {% if  e.elementeimages_set.all.count %}
                    <img src="uploads/{{e.elementeimages_set.all.0.cover}} " alt="{{e.elementeimages_set.all.0.title}}" title="{{e.elementeimages_set.all.0.title}}">
                    {% else %}

                    <img src="uploads/{{e.elementeimages_set.all.0.cover}} " alt=""> {#imagen pro defecto#}
                {% endif %}
                    
                    
                    <h3>
                        {{e.title}}
                    </h3>

                    <strong>$ {{e.price}}</strong> <br>
                    <a href=" {% url 'store:detalle' e.id %}">ver id</a>
                    <a href=" {% url 'store:detalle' e.id e.url_clean %}">ver id/slug</a>
                    <a href=" {% url 'store:detalle' e.url_clean %}">ver slug</a>
                </div>
            </div>
        </div>

                {% endfor %}

            </div>
</body>

</html>

templates/store/index_old.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
            <!--Bootsrap 4 CDN-->
            <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
            integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO"
            crossorigin="anonymous">

    <!--Fontawesome CDN-->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css"
            integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU"
            crossorigin="anonymous">

    <!--Custom styles-->
    <link rel="stylesheet" type="text/css" href="styles.css">

    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet"
            id="bootstrap-css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <!------ Include the above in your HEAD tag ---------->
</head>
<body class="container h-75">

    <h1> Tienda la esquina</h1>

    <form method="get" class="form-inline">
        <input  type="text" name="search" id="  " value="{{search}}" class="form-control w-75">
        <select name="category_id" id=""  class="form-control">
            <option value="sin selección">sin selección</option>
            {% for c in category %}                
              <option value="{{c.id}}"
              {% if category_id == c.id %}
                selected
                {% endif %}
              >{{c.title}} </option>
            {% endfor %}

        </select>

        <button type="submit">Buscar</button>

    </form>

    {% for e in elements %}
        <div class="card-header mt-2"></div>
        <div class="card">
            <div class="card-body">
            <h3>
                {{e.title}}
            </h3>
            <p>
                {{e.description| truncatechars:'200'}}
               
            </p>
            <a href=" {% url 'store:detalle' e.id %}">ver id</a>
            <a href=" {% url 'store:detalle' e.id e.url_clean %}">ver id/slug</a>
            <a href=" {% url 'store:detalle' e.url_clean %}">ver slug</a>
        </div>
    </div>
      
    {% endfor %}

</body>
</html>